/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import business.Business;
import business.Customer.CustomerDirectory;
import business.Order.Order;
import business.Order.OrderDirectory;
import business.Restaurant.RestaurantDirectory;
import business.useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author deepv
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    Business business;
    RestaurantDirectory restaurantDirectory;
    CustomerDirectory customerDirectory;
    OrderDirectory orderDirectory;
    UserAccount account;

    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Business business, RestaurantDirectory restaurantDirectory, CustomerDirectory customerDirectory, OrderDirectory orderDirectory) {
        initComponents();
        this.business = business;
        this.restaurantDirectory = restaurantDirectory;
        this.customerDirectory = customerDirectory;
        this.orderDirectory = orderDirectory;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        NavigationJPanel = new javax.swing.JPanel();
        btnRestaurant = new javax.swing.JButton();
        btnDeliveryStaff = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        workAreaPanel = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(240, 255, 255));

        NavigationJPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnRestaurant.setBackground(new java.awt.Color(206, 217, 217));
        btnRestaurant.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRestaurant.setForeground(new java.awt.Color(0, 51, 51));
        btnRestaurant.setText("MANAGE RESTAURANTS");
        btnRestaurant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurantActionPerformed(evt);
            }
        });

        btnDeliveryStaff.setBackground(new java.awt.Color(206, 217, 217));
        btnDeliveryStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeliveryStaff.setForeground(new java.awt.Color(0, 51, 51));
        btnDeliveryStaff.setText("MANAGE DELIVERY STAFF");
        btnDeliveryStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeliveryStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveryStaffActionPerformed(evt);
            }
        });

        btnCustomers.setBackground(new java.awt.Color(206, 217, 217));
        btnCustomers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCustomers.setForeground(new java.awt.Color(0, 51, 51));
        btnCustomers.setText("MANAGE CUSTOMERS");
        btnCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavigationJPanelLayout = new javax.swing.GroupLayout(NavigationJPanel);
        NavigationJPanel.setLayout(NavigationJPanelLayout);
        NavigationJPanelLayout.setHorizontalGroup(
            NavigationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NavigationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeliveryStaff, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRestaurant, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(NavigationJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCustomers)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NavigationJPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCustomers, btnDeliveryStaff, btnRestaurant});

        NavigationJPanelLayout.setVerticalGroup(
            NavigationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationJPanelLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(btnRestaurant, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnDeliveryStaff)
                .addGap(45, 45, 45)
                .addComponent(btnCustomers)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        NavigationJPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCustomers, btnDeliveryStaff, btnRestaurant});

        jSplitPane1.setLeftComponent(NavigationJPanel);

        workAreaPanel.setBackground(new java.awt.Color(255, 255, 255));
        workAreaPanel.setToolTipText("");
        workAreaPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workAreaPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1005, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurantActionPerformed
        JPanel manageRestaurantManagersPanel = new ManageRestaurantManagersPanel(business, account, workAreaPanel, restaurantDirectory);
        workAreaPanel.add("ManageRestaurantManagersPanel", manageRestaurantManagersPanel);
        CardLayout layout = (CardLayout) workAreaPanel.getLayout();
        layout.next(workAreaPanel);
    }//GEN-LAST:event_btnRestaurantActionPerformed

    private void btnDeliveryStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeliveryStaffActionPerformed
        JPanel manageDeliveryStaffPanel = new ManageDeliveryStaffPanel(business);
        workAreaPanel.add("ManageDeliveryStaffPanel", manageDeliveryStaffPanel);
        CardLayout layout = (CardLayout) workAreaPanel.getLayout();
        layout.next(workAreaPanel);    }//GEN-LAST:event_btnDeliveryStaffActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        JPanel manageCustomerPanel = new ManageCustomerPanel(business, customerDirectory);
        workAreaPanel.add("ManageCustomerPanel", manageCustomerPanel);
        CardLayout layout = (CardLayout) workAreaPanel.getLayout();
        layout.next(workAreaPanel);    }//GEN-LAST:event_btnCustomersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NavigationJPanel;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnDeliveryStaff;
    private javax.swing.JButton btnRestaurant;
    private javax.swing.JButton jButton1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel workAreaPanel;
    // End of variables declaration//GEN-END:variables
}
